# Primary nginx reverse proxy that connects to ConfigurableHTTPServer
server {
    listen 80;

    location / {
        proxy_pass http://unix:/run/jupyterhub/chp.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header REMOTE_USER "alice"; # for this example, we simply mock the value of this header, which in production would be passed in by a trusted auth server.
        # this means that when connecting to this server via the browser, you will also authenticate as alice.
    }
}

# The sockets in /run/jupyterhub must be accessible only by nginx and user jupyter (the hub).
# However, single-user servers spawned by the Hub must be able to access the Hub's api, and they run under the uid of normal users.
# So we need to provided an endpoint for normal users to access the Hub's api.
# We can secure this endpoint by only accepting requests to /hub/api, which requires an API key provided to single-user servers by the Hub for auth, instead of REMOTE_USER header.
# Since this is a public endpoint, we could make it listen on a TCP socket, but since we're using unix sockets everywhere, let's do that!
server {
  listen unix:/jupyterhub_public/jupyterhub_api.sock;
  location /hub/api {
        proxy_pass http://unix:/run/jupyterhub/jupyterhub.sock;
        # This proxy only accepts requests to /hub/api, which uses auth tokens instead of REMOTE_USER auth.
        # Still, let's also remove the REMOTE_USER header for good measure
        proxy_set_header REMOTE_USER "";
  }
}
