# Configuration for the primary NGINX reverse proxy for JupyterHub
server {
    # Listen for incoming HTTP traffic on port 80
    listen 80;

    # Proxy all requests to the JupyterHub configurable HTTP proxy
    location / {
        proxy_pass http://unix:/run/jupyterhub/chp.sock;

        # Pass client-side details to the upstream server
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Set REMOTE_USER to a fixed value ('alice') for demonstration purposes only.
        # In production, this value will originate from an external authentication provider.
        proxy_set_header REMOTE_USER "alice";

        # Note: All connections will be identified as "alice" when testing this setup.
    }
}

# Additional server to expose a public endpoint for the Hub's API
server {
    # Listen using a Unix socket instead of a TCP socket for local communications.
    # Since this is a public endpoint, this is not strictly necessary -- but since we're illustrating UDS, let's use a UDS instead of TCP port!
    listen unix:/jupyterhub_public/jupyterhub-api.sock;

    # Restrict requests to /hub/api only
    # This route requires API tokens for authentication, not REMOTE_USER.
    # The Hub provided a single-user server with its own API key when it is spawned.
    # So only Hub-spawned processses will be able to connect.
    location /hub/api {
        proxy_pass http://unix:/run/jupyterhub/jupyterhub.sock;

        # Remove the REMOTE_USER header for good measure.
        proxy_set_header REMOTE_USER "";

        # Note: API endpoints require authorization, which is granted via unique API keys from the Hub.
        # User tokens authenticate single-user servers, ensuring security at this endpoint.
    }
}
