server {
    listen 80;

    location / {
        proxy_pass http://unix:/run/jupyterhub/chp.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header REMOTE_USER "alice";
    }
}

server {
  listen unix:/jupyterhub_public/jupyterhub_api.sock;
  location / {
        proxy_pass http://unix:/run/jupyterhub/jupyterhub.sock;
        # Remove the REMOTE_USER header so thatclients that connect to this socket from localhost are not authenticated with the Hub.
        # This limits access to the Hub from clients on localhost to the Hub's API (/api route), which requires a valid API auth token.
        # Applications spawned by the Hub are provisioned with a valid API token. Other clients will be unable to authenticate with the Hub.
        proxy_set_header REMOTE_USER "";
  }
}